{% set name = "robobrowser" %}
{% set version = "0.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 31219acab41ca68adce928e5c1e04acebba4ceabeb447b9c5e408d7b30fee983

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - beautifulsoup4 >=4.3.2
    - requests >=2.6.0
    - six >=1.9.0
    - werkzeug >=0.10.4

test:
  requires:
    - python {{ python_min }}
  imports:
    - robobrowser

about:
  home: http://github.com/jmcarp/robobrowser
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Your friendly neighborhood web scraper'
  description: |
    RoboBrowser is a simple, Pythonic library for browsing the web without a
    standalone web browser. RoboBrowser can fetch a page, click on links and
    buttons, and fill out and submit forms. If you need to interact with web
    services that don't have APIs, RoboBrowser can help.
  doc_url: http://robobrowser.readthedocs.org/
  dev_url: https://github.com/jmcarp/robobrowser

extra:
  recipe-maintainers:
    - djsutherland
